---
Name: DownloadModule
---
#Overwrite in own project if needed
DownloadModuleConfig:
  CategoriesHaveContent: false
  #CSV-Style
  CategoryStyles: "Style A"
  CategoriesEnabled: true
  CanCreatePages: true
  ModelAdminVisible: true
  PreviewImageEnabled: true
