---
Name: DownloadModule
---
#Overwrite in own project if needed
DownloadModuleConfig:
  SubCategoriesEnabled: false
  SubDownloadsEnabled: false
  CategoriesHaveContent: false
  #CSV-Style
  CategoryStyles: "Style A"
  UseCategoryStylesForSubCategories: false
  #CSV-Style
  SubCategoryStyles: "Style A"
